apiVersion: operator.kubermatic.io/v1alpha1
kind: KubermaticConfiguration
metadata:
  name: kubermatic
  namespace: kubermatic
spec:
  # These secret keys configure the way components commmunicate with Dex.
  auth:
    clientID: kubermatic
    # these need to be randomly generated. Those can be generated on the shell using:
    # cat /dev/urandom | tr -dc A-Za-z0-9 | head -c32
    issuerCookieKey: TODO-A-RANDOM-ISSUERCOOKIEKEY
    serviceAccountKey: TODO-A-RANDOM-SERVICEACCOUNTKEY
  ingress:
    # this domain must match what you configured as dex.ingress.host
    # in the values.yaml
    domain: kubermatic.TODO-STUDENT-DNS.loodse.training
    certificateIssuer:
      name: letsencrypt-prod